### ISSUE TITLE
Can't update Reverse Relations field after initial save

### ISSUE THREAD

**Issue by robmcfadden** [robuust/craft-reverserelations#27]
I have a Reverse Entry Relations field configured. I can relate to it from the target entries field, but I cannot update the Reverse Entry Relations field after the initial save of its entry. If I create a new entry that has the reverse field, I can add entries. If I save and try to add more, they do not stick.

I'm trying this on a fresh Craft install with no other plugins added. Thanks in advance for taking a look!

PHP version - 7.4.2
Database driver & version - MySQL 5.7.26
Craft edition & version - Craft Solo 3.7.8
Reverse Relations - 1.2.5

**Comment by boboldehampsink** [comment]
Confirmed, looking into this.

**Comment by boboldehampsink** [comment]
It seems like the new Craft draft/revision/entry handling doesn't work with this plugin anymore. I have spent several hours trying to fix this, but to no success.

**Comment by boboldehampsink** [comment]
Problem is this: when `afterElementSave` is run I try to get the field's value by running `$element->getFieldValue($this->handle)->anyStatus()->all()` - but all I get is an empty array (while the UI says there are elements). Maybe @brandonkelly knows where to look?

**Comment by brandonkelly** [comment]
The issue here is that Reverse Entries fields don’t store their own values; they just modify other elements’ relations, pointing them to the current target element. And when you’re editing a draft, the current element is the draft, not the canonical entry. When the draft is applied to the canonical entry, any relations that were pointing to it are lost.

I’ve fixed it in #28 this by having the field only ever manage relations to the canonical entry, not its drafts. Which is a bit awkward because changes take effect _immediately_ even though they appear to only be modified on the (provisional) draft.

A better implementation might be to have the field start storing its expected relations in the `content` table, and only actually modify the `relations` table when a canonical entry is being updated. But that would be quite a bit more involved and maybe not worth the effort. It also could end up causing newer relations created after the draft was created, to be deleted when the draft is applied.

**Comment by boboldehampsink** [comment]
Awesome Brandon! Thanks for the help. @robmcfadden 1.3.0 is out now with Craft 3.7 compatibility 🎉
