### ISSUE TITLE
Craft 5.3

### ISSUE THREAD

**Issue by JeroenJRP** [robuust/craft-reverserelations#45]
The changes in Craft 5.3 that made relation fields multi-instance (https://github.com/craftcms/cms/pull/15400) break the functionality of this plugin.

The immediate problem is that the `is_array($value)` check in `normalizeValue` always returns `true` now, skipping the plugin logic. But there are probably other implications.

**Comment by boboldehampsink** [comment]
Thanks, will have to look into this. For now, I have released 3.0.1 which has a constraint on Craft CMS < 5.3.

**Comment by Marcuzz** [comment]
The issue occurs because the default value of a BaseRelationField has changed: https://github.com/craftcms/cms/pull/15400/files#diff-dd150284a0df94daa2918aaacda81e6ad9b20bac8d429414043f37120a5769ddR100-R103

Since the default value for a BaseRelationField is no longer `null` we now run into two problems:

1. We never enter the following clause, as mentioned by OP: https://github.com/robuust/craft-reverserelations/blob/develop/src/fields/ReverseEntries.php#L54 – the side effect of this is that we never render the reverse relation list in the UI.
2. Because the default value is now an array, we always enter the following condition in BaseRelationField when viewing a regular entries field: https://github.com/craftcms/cms/blob/5.x/src/fields/BaseRelationField.php#L670 – previously the entire logic for grabbing the list of relations hinged on entering this clause: https://github.com/craftcms/cms/blob/5.x/src/fields/BaseRelationField.php#L679. It seems like this is now legacy code, and the code for saving a relation has to be updated because relation fields are now "multi instance".

**Edit**: You can fix the ReverseEntries field itself by overriding dbType: https://github.com/Marcuzz/craft-reverserelations/blob/develop/src/fields/ReverseEntries.php#L40-L43

This works if you have a read only field from the ReverseEntries field side, but editing from that side still requires a fix in the code that saves relations.

**Comment by Marcuzz** [comment]
An update to my previous comment ☝️ 

These changes fixes all the aforementioned issues, and makes it compatible with 5.3: https://github.com/robuust/craft-reverserelations/compare/develop...Marcuzz:craft-reverserelations:develop

Let me know if you would like me to submit a PR 😄

**Comment by boboldehampsink** [comment]
Thanks, will look into it the coming days. No PR needed.

**Comment by boboldehampsink** [comment]
3.0.2 is out now with this fix, thanks a lot @Marcuzz !
